services:
  desafio2_database:
    image: postgres:15-alpine
    container_name: desafio2-db-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio2
    volumes:
      - desafio2_data_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - desafio2_network

  desafio2_reader:
    image: postgres:15-alpine
    container_name: desafio2-reader-container
    depends_on:
      - desafio2_database
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - desafio2_network
    volumes:
      - desafio2_data_volume:/var/lib/postgresql/data

networks:
  desafio2_network:
    driver: bridge

volumes:
  desafio2_data_volume:
