version: "3.8"

services:
  desafio3_database:
    image: postgres:15-alpine
    container_name: desafio3-database
    environment:
      POSTGRES_USER: desafio_user
      POSTGRES_PASSWORD: desafio_password
      POSTGRES_DB: desafio3_app_db
    volumes:
      - desafio3_dbdata:/var/lib/postgresql/data
    networks:
      - desafio3_network
    restart: always

  desafio3_cache:
    image: redis:alpine
    container_name: desafio3-cache-service
    networks:
      - desafio3_network
    restart: always

  desafio3_web:
    image: busybox
    container_name: desafio3-web-service
    depends_on:
      - desafio3_database
      - desafio3_cache
    environment:
      DB_HOST: desafio3_database
      DB_USER: desafio_user
      DB_PASSWORD: desafio_password
      CACHE_HOST: desafio3_cache
      CACHE_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - desafio3_network
    entrypoint: ["sh", "-c", "echo 'Aplicação Web do Desafio 3 em execução...' && tail -f /dev/null"]
    restart: always

networks:
  desafio3_network:
    driver: bridge

volumes:
  desafio3_dbdata:
