services:
  api-gateway:
    image: nginx:alpine
    container_name: desafio5-api-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - desafio5_network
    depends_on:
      - users-service
      - orders-service
    restart: always

  users-service:
    build: ./service_users
    container_name: desafio5-users-service
    networks:
      - desafio5_network
    restart: always

  orders-service:
    build: ./service_orders
    container_name: desafio5-orders-service
    networks:
      - desafio5_network
    restart: always

networks:
  desafio5_network:
    driver: bridge
